version: '3.8'

x-cache-from:
  - &app-cache-from
    cache_from:
      - php:8.0-fpm

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080


  php:
    image: php:8.0-fpm
    build:
      context: ./docker/php-fpm
      <<: *app-cache-from
    depends_on:
      - db
    environment:
      - APP_ENV=${APP_ENV}
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s
    volumes:
      - ./:/var/www
      - app-cache:/var/www/var

  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php
      - mailcatcher
    ports:
      - "80:80"
      - "443:443"

  # mailcatcher:
  #   image: schickling/mailcatcher
  #   ports:
  #     - "1080:1080"

volumes:
  db-data: {}
  app-cache: {}
